
spring:
  datasource:
    url: jdbc:mysql://interchange.proxy.rlwy.net:36198/ragdb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true #jdbc:mysql://localhost:3306/ragdb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true   #jdbc:h2:mem:retaidai;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
   # driverClassName: org.h2.Driver
   # url: jdbc:mysql://localhost:3306/ragdb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
    username: root #sa
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        open-in-view: false
        sql:
          init:
            mode: never
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      location: ${app.upload-dir}
      max-file-size: 25MB
      max-request-size: 25MB

server:
  port: 8082

app:
  name: ai-retail-assistant
  seed:
    enabled: true

  upload-dir: uploads
  llm:
    provider: ollama
    model: llama3 #gemma3:12b #deepseek-r1:8b #llama3  #mistral #llama3     # Using the model you already have
    base-url: http://localhost:11434
    api-key: ""
    # Timeout settings (in milliseconds)
    connect-timeout: 10000    # 10 seconds for connection
    read-timeout: 80000       # 60 seconds for response (increase if using larger models)


  ocr:
    provider: ocrspace         # ocrspace | local (tesseract) | textract
    ocrspace:
      apikey: K83149892088957   # set env var or paste a key here
      language: eng                # e.g., eng or eng+hin (hin=Hindi)
      engine: 2                    # 2=default/fast; 5=experimental (sometimes better)

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: method
  profiles:
   active: mysql

qcall:
  base-url: https://api.qcall.ai/api/v1
  api-key: 39c0a97e-befd-4476-aa5e-14699734cadd   # put the real key in env var QCALL_API_KEY
rag:
  api:
    baseUrl: http://localhost:8089
    connectTimeout: 5s
    readTimeout: 120s

    endpoints:
      text: /v1/documents:text
      file: /v1/documents:file
      url:  /v1/documents:url
      ask:  /v1/ask
      reindex: /v1/admin/reindex
    externalRag: true